### ISSUE TITLE
Code example doesn't work

### ISSUE THREAD

**Issue by pgdagenais** [albshin/go-pubg#2]
The change made in this pull request https://github.com/albshin/go-pubg/pull/1 break my code
I'm new to go, but this is my code:
```GO
package main

import (
  "fmt"
  "github.com/albshin/go-pubg"
)

func main() {
  client := pubg.New("MYAPIKEY")
  info, _ := client.GetPlayer("Break")      
  fmt.Printf("%+v\n", info)
}
```

And this is the error that I get:
```
$ go build
# github.com/pgdagenais/app
./app.go:9: multiple-value pubg.New() in single-value context
```

I went back to the old version of the `New()` function and I am able to build my app

**Comment by mgerb** [comment]
Woops, one thing I missed before. I'll submit another PR fixing the readme.

pubg.New() now returns multiple values. This is a common pattern in Go to handle errors. You can see in the error message that pubg.new() is 'multiple value' and it's trying to be using in a single value context because you are only assigning one value to it.

Here is a solution:

```
client, _ := pubg.New("MYAPIKEY")
```

Or if you wanted to check for an error:

```
client, err := pubg.New("MYAPIKEY")

if err != nil {
  log.Fatal(err)
}
```

**Comment by pgdagenais** [comment]
Awesome thank you very much !

**Comment by albshin** [comment]
Closing issue.
